steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_GCP_PROJECT_ID}/${_REPO_NAME}:${COMMIT_SHA}', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_GCP_PROJECT_ID}/${_REPO_NAME}:${COMMIT_SHA}']

  # Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${_GCP_PROJECT_ID}/${_REPO_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

substitutions:
  _GCP_PROJECT_ID: 'noted-reef-387021'
  _REPO_NAME: 'cloud-run-source-deploy'  # Changed from _APP_NAME to _REPO_NAME to match your GCR repository name
  _SERVICE_NAME: 'mickeyf-org'
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
