steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_GCP_PROJECT_ID}/${_APP_NAME}:${COMMIT_SHA}', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_GCP_PROJECT_ID}/${_APP_NAME}:${COMMIT_SHA}']

substitutions:
  _GCP_PROJECT_ID: 'noted-reef-387021'
  _APP_NAME: 'mickeyf-org' 

options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: 'gs://mickeyf-logs'