version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=https://mickeyf-org-j7yuum4tiq-uc.a.run.app/api/users
    depends_on:
      - cloudsql-proxy

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: /cloud_sql_proxy -instances=noted-reef-387021:us-central1:cms-mickeyf=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - API_URL=http://backend:8080
