name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install
        working-directory: frontend
        env:
          NODE_ENV: 'production'
          DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
          PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
          DEV_API_URL: ${{ secrets.DEV_API_URL }}
          PROD_API_URL: ${{ secrets.PROD_API_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}

      - name: Build the project
        run: npm run prod && npm run postbuild
        working-directory: frontend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTED_REEF_387021 }}
          channelId: live
          projectId: noted-reef-387021
